function nomearDataComemorativa() {
    const hoje = new Date();
    const dia = hoje.getDate();
    const mes = hoje.getMonth() + 1; // Os meses em JavaScript começam do zero

    // Mapeamento de datas comemorativas
    const datasComemorativas = {
        //JANEIRO
        '01/02': 'Dia do Sanitarista - Janeiro',
        '01/03': 'Dia do Hemofílico, Dia da Abreugrafia - Janeiro',
        '01/04': 'Dia Mundial do Braile - Janeiro',
        '01/05': 'Dia Nacional da Tipografia - Janeiro',
        '01/06': 'Dia de Reis, Dia da Gratidão - Janeiro',
        '01/07': 'Dia do Leitor, Dia do Mensageiro, Dia da Liberdade de Culto - Janeiro',
        '01/08': 'Dia da Fotografia, Dia do Fotógrafo - Janeiro',
        '01/09': 'Dia do Fico (em 1822), Dia do Astronauta - Janeiro',
        '01/10': 'Dia de São Gonçalo, Dia de Peculiar People Play - Janeiro',
        '01/11': 'Dia de São Teodósio - Janeiro',
        '01/12': 'Dia do Empresário Contábil - Janeiro',
        '01/14': 'Dia do Sargento, Dia do Treinador de Futebol - Janeiro',
        '01/15': 'Dia do Compositor - Janeiro',
        '01/16': 'Dia do Cortador de Cana-de-Açúcar - Janeiro',
        '01/18': 'Dia da Manicure - Janeiro',
        '01/19': 'Dia Oficial do Cabeleireiro, Dia do Terapeuta Ocupacional - Janeiro',
        '01/20': 'Dia do Farmacêutico, Dia da Parteira Tradicional - Janeiro',
        '01/25': 'Dia do Carteiro - Janeiro',
        '01/27': 'Dia do Orador - Janeiro',
        '01/28': 'Dia do Portuário, Dia do Auditor Fiscal do Trabalho - Janeiro',
        '01/31': 'Dia do Mágico, Dia do Engenheiro Ambiental - Janeiro',
        //FEVEREIRO
        '02/01': 'Dia do Publicitário - Fevereiro',
        '02/02': 'Dia de Jesus Cristo, Dia de Nossa Senhora dos Navegantes, Dia do Agente Fiscal - Fevereiro',
        '02/05': 'Dia do Datiloscopista, Dia do Dermatologista - Fevereiro',
        '02/06': 'Dia do Agente de Defesa Ambiental - Fevereiro',
        '02/07': 'Dia do Gráfico - Fevereiro',
        '02/10': 'Dia do Atleta Profissional - Fevereiro',
        '02/11': 'Dia do Zelador - Fevereiro',
        '02/13': 'Carnaval (Data móvel) - Fevereiro',
        '02/14': 'Quarta-feira de cinzas (Data móvel) - Fevereiro',
        '02/16': 'Dia do Repórter - Fevereiro',
        '02/22': 'Dia do Auxiliar de Serviços Gerais - Fevereiro',
        '02/24': 'Promulgação da primeira Constituição da República do Brasil (1891) - Fevereiro',
        '02/27': 'Dia do Agente Fiscal da Receita Federal - Fevereiro',

        //MARÇO
        '03/07': 'Dia do Fuzileiro Naval, Dia do Paleontólogo - Março',
        '03/08': 'Dia Internacional da Mulher - Março',
        '03/09': 'Dia do DJ - Março',
        '03/12': 'Dia do Bibliotecário - Março',
        '03/14': 'Dia dos Carecas - Março',
        '03/15': 'Dia do Consumidor - Março',
        '03/16': 'Dia do Agente Penitenciário Federal, Dia Nacional do Ouvidor - Março',
        '03/17': 'Dia de São Patrício - Março',
        '03/19': 'Dia do Caráter, Dia do Carpinteiro e do Marceneiro, Dia do Consertador, Dia Nacional do Artesão - Março',
        '03/20': 'Início do Outono - Março',
        '03/23': 'Dia do Optometrista - Março',
        '03/27': 'Dia Mundial do Teatro, Dia do Graffiti - Março',
        '03/28': 'Dia do Diagramador, Dia do Revisor - Março',

        //ABRIL
        '04/01': 'Dia da Mentira, Dia da Abolição da Escravidão dos Índios - Abril',
        '04/02': 'Dia Mundial de Conscientização do Autismo, Dia do Propagandista, Dia Internacional do Livro Infantil - Abril',
        '04/04': 'Dia Nacional do Parkinsoniano - Abril',
        '04/05': 'Dia do Propagandista Farmacêutico - Abril',
        '04/07': 'Dia do Corretor, Dia do Jornalista, Dia Mundial da Saúde, Dia do Médico Legista - Abril',
        '04/08': 'Dia Mundial de Combate ao Câncer, Dia Mundial da Astronomia, Dia Nacional do Sistema Braile - Abril',
        '04/10': 'Dia do Engenheiro Metalurgista - Abril',
        '04/11': 'Dia do Infectologista - Abril',
        '04/12': 'Dia do Humorista, Dia do Obstetra - Abril',
        '04/13': 'Dia do Office Boy - Abril',
        '04/14': 'Dia do Técnico em Serviço de Saúde, Dia do Neurocirurgião - Abril',
        '04/15': 'Dia do Desarmamento Infantil, Dia Internacional do Ciclista - Abril',
        '04/18': 'Dia Nacional do Livro Infantil, Dia Mundial do Radiamador - Abril',
        '04/19': 'Dia do Índio - Abril',
        '04/20': 'Dia do Diplomata - Abril',
        '04/21': 'Dia de Tiradentes (Inconfidência Mineira), Inauguração de Brasília (1960), Dia do Funcionário Policial Civil, Dia do Metalúrgico, Dia do Têxtil - Abril',
        '04/22': 'Dia do Descobrimento do Brasil (1500), Dia do Agente de Viagem - Abril',
        '04/23': 'Dia de São Jorge, Dia do Escoteiro, Dia do Serralheiro - Abril',
        '04/24': 'Dia de Libras (Língua Brasileira de Sinais), Dia Mundial do Livro - Abril',
        '04/25': 'Dia do Despachante Aduaneiro, Dia do Profissional da Contabilidade - Abril',
        '04/26': 'Dia do Engraxate, Dia do Goleiro, Dia do Juiz Trabalhista - Abril',
        '04/27': 'Dia da Empregada Doméstica - Abril',
        '04/28': 'Dia da Educação, Dia da Sogra - Abril',
        '04/29': 'Dia Internacional da Dança - Abril',
        '04/30': 'Dia Nacional da Mulher, Dia do Ferroviário - Abril',

        //MAIO
        '05/01': 'Dia do Trabalhador - Maio',
        '05/03': 'Dia do Taquígrafo - Maio',
        '05/05': 'Dia Internacional da Parteira, Dia do Cartógrafo, Dia do Psicanalista - Maio',
        '05/06': 'Dia Nacional da Matemática, Dia do Cartógrafo, Dia do Psicanalista - Maio',
        '05/07': 'Dia Mundial do Silêncio, Dia do Oftalmologista - Maio',
        '05/08': 'Dia do Artista Plástico Brasileiro, Dia do Profissional de Marketing - Maio',
        '05/10': 'Dia Nacional do Guia de Turismo, Dia da Cozinheira - Maio',
        '05/12': 'Dia do Engenheiro Militar, Dia Internacional da Enfermagem e do Enfermeiro, Dia das Mães (Segundo domingo de maio) - Maio',
        '05/13': 'Dia da Abolição da Escravatura, Dia do Chefe de Cozinha, Dia de Nossa Senhora de Fátima, Dia do Zootecnista - Maio',
        '05/15': 'Dia do Cortejo, Dia do Assistente Social, Dia do Gerente Bancário - Maio',
        '05/16': 'Dia dos Cientistas, Dia do Gari - Maio',
        '05/17': 'Dia Internacional da Luta Contra à Homofobia, Dia Internacional da Comunicação - Maio',
        '05/18': 'Dia Nacional de Combate ao Abuso e à Exploração Sexual de Crianças e Adolescentes, Dia dos Vidraceiros - Maio',
        '05/19': 'Dia do Profissional de Física, Dia do Defensor Público - Maio',
        '05/20': 'Dia do Comissário de Menores, Dia Nacional do Técnico e Auxiliar de Enfermagem, Dia do Pedagogo - Maio',
        '05/22': 'Dia do Apicultor - Maio',
        '05/23': 'Dia do Sol - Maio',
        '05/24': 'Dia da Indústria Gráfica, Dia da Lua, Dia do Datilógrafo, Dia do Telegrafista - Maio',
        '05/25': 'Dia da Indústria e do Industrial, Dia da Costureira, Dia do Massagista, Dia do Trabalhador Rural - Maio',
        '05/26': 'Dia do Revendedor Lotérico - Maio',
        '05/27': 'Dia do Profissional Liberal - Maio',
        '05/28': 'Dia de Ação pela Saúde da Mulher, Dia Mundial Contra a Mortalidade Materna, Dia do Ceramista - Maio',
        '05/29': 'Dia do Geógrafo e do Estatístico, Dia do Ferroviário - Maio',
        '05/30': 'Dia do Geólogo, Dia do Decorador - Maio',
        '05/31': 'Dia da Aeromoça e do Comissário de Voo - Maio',

        //JUNHO
        '06/03': 'Dia Internacional do Administrador de Pessoal e da Comunidade Social, Dia do Profissional de Recursos Humanos - Junho',
        '06/04': 'Dia do Engenheiro Agrimensor - Junho',
        '06/05': 'Dia Mundial do Meio Ambiente - Junho',
        '06/08': 'Dia do Cunhado, Dia do Citricultor, Dia do Oceanógrafo - Junho',
        '06/09': 'Dia do Porteiro, Dia do Tenista - Junho',
        '06/11': 'Dia da Marinha Brasileira, Dia do Educador Sanitário - Junho',
        '06/12': 'Dia dos Namorados, Dia Mundial contra o Trabalho Infantil - Junho',
        '06/13': 'Dia de Santo Antônio - Junho',
        '06/14': 'Dia do Solista - Junho',
        '06/17': 'Dia do Gestor Comercial - Junho',
        '06/18': 'Dia do Químico - Junho',
        '06/19': 'Dia do Cinema Brasileiro - Junho',
        '06/20': 'Dia do Advogado Trabalhista, Dia do Revendedor, Dia do Vigilante, Início do Inverno (2024) - Junho',
        '06/21': 'Dia do Profissional de Mídia, Dia do Aeroviário, Dia do Economiário, Dia do Orquidófilo - Junho',
        '06/22': 'Dia do Descobrimento do Brasil (1500), Dia do Agente de Viagem - Junho',
        '06/23': 'Dia de São João, Dia Nacional do Policial e do Bombeiro Militares, Dia do Observador Aéreo - Junho',
        '06/26': 'Dia do Metrologista - Junho',
        '06/27': 'Dia Nacional do Quadrilheiro Junino - Junho',
        '06/28': 'Dia Internacional do Orgulho LGBTQIA+ - Junho',
        '06/29': 'Dia de São Pedro, Dia de São Paulo (Santo), Dia do Dublador, Dia do Engenheiro de Petróleo, Dia do Papa, Dia do Pescador, Dia do Telefonista - Junho',
        '06/30': 'Dia Nacional do Fiscal Federal Agropecuário - Junho',

        //JULHO
        '07/02': 'Independência da Bahia, Dia do Bombeiro Brasileiro - Julho',
        '07/04': 'Dia do Operador de Telemarketing - Julho',
        '07/08': 'Dia Nacional do Pesquisador, Dia do Panificador - Julho',
        '07/10': 'Dia do Engenheiro de Minas - Julho',
        '07/12': 'Dia do Engenheiro Florestal - Julho',
        '07/13': 'Dia Mundial do Rock, Dia do Cantor, Dia do Engenheiro de Saneamento, Dia dos Compositores e Cantores Sertanejos - Julho',
        '07/14': 'Dia do Engenheiro de Aquicultura, Dia do Propagandista de Laboratório, Dia do Administrador Hospitalar - Julho',
        '07/15': 'Dia do Engenheiro de Aquicultura, Dia do Propagandista de Laboratório, Dia do Administrador Hospitalar - Julho',
        '07/16': 'Dia do Comerciante, Dia do Engenheiro de Alimentos - Julho',
        '07/20': 'Dia do Amigo, Dia Pan-americano do Engenheiro - Julho',
        '07/21': 'Dia Nacional do Garimpeiro, Dia do Cantor Lírico - Julho',
        '07/22': 'Dia do Cantor Lírico, Dia do Aeroviário, Dia do Economiário, Dia do Orquidófilo - Julho',
        '07/23': 'Dia do Guarda Rodoviário - Julho',
        '07/24': 'Dia Nacional do Suinocultor - Julho',
        '07/25': 'Dia do Escritor, Dia do Motorista - Julho',
        '07/26': 'Dia dos Avós, Dia Nacional do Arqueólogo - Julho',
        '07/27': 'Dia do Motociclista, Dia do Pediatra - Julho',
        '07/28': 'Dia do Agricultor - Julho',
        '07/31': 'Dia Mundial do Guarda-Florestal - Julho',

        //AGOSTO
        '08/01': 'Dia do Cerealista - Agosto',
        '08/03': 'Dia do Tintureiro - Agosto',
        '08/04': 'Dia do Padre, Dia do Sacerdote - Agosto',
        '08/06': 'Dia Nacional dos Profissionais da Educação - Agosto',
        '08/11': 'Dia do Estudante, Dia do Advogado, Dia do Garçom, Dia do Magistrado, Dia dos Pais (Segundo domingo de agosto) - Agosto',
        '08/13': 'Dia Mundial do Canhoto, Dia do Economista - Agosto',
        '08/14': 'Dia do Cardiologista - Agosto',
        '08/15': 'Assunção de Nossa Senhora - Agosto',
        '08/16': 'Dia do Filósofo, Dia do Auxiliar de Almoxarifado - Agosto',
        '08/19': 'Dia do Artista de Teatro, Dia do Historiador - Agosto',
        '08/22': 'Dia do Folclore, Dia do Supervisor e Coordenador - Agosto',
        '08/23': 'Dia do Susto, Dia do Aviador Naval - Agosto',
        '08/25': 'Dia do Soldado, Dia do Feirante, Dia do Miojo - Agosto',
        '08/26': 'Dia do Catequista - Agosto',
        '08/27': 'Dia do Psicólogo, Dia do Corretor de Imóveis - Agosto',
        '08/28': 'Dia dos Bancários - Agosto',
        '08/31': 'Dia do Nutricionista - Agosto',

        //SETEMBRO
        '09/01': 'Dia do Profissional de Educação Física - Setembro',
        '09/02': 'Dia do Florista, Dia do Repórter Fotográfico - Setembro',
        '09/03': 'Dia Nacional do Biólogo, Dia do Guarda Civil - Setembro',
        '09/05': 'Dia da Amazônia, Dia dos Irmãos, Dia do Oficial de Farmácia do Brasil - Setembro',
        '09/06': 'Dia do Alfaiate - Setembro',
        '09/07': 'Dia da Proclamação da Independência do Brasil, Dia Internacional de Conscientização sobre Distrofia Muscular de Duchenne - Setembro',
        '09/08': 'Dia de Nossa Senhora, Maria, Mãe de Jesus, Dia do Administrador, Dia do Médico Veterinário - Setembro',
        '09/10': 'Dia Nacional do Assessor de Imprensa - Setembro',
        '09/11': 'Dia Nacional do Cerrado, Dia do Árbitro Esportivo - Setembro',
        '09/12': 'Dia do Operador de Rastreamento - Setembro',
        '09/13': 'Dia do Programador, Dia do Agrônomo - Setembro',
        '09/15': 'Dia do Cliente - Setembro',
        '09/16': 'Dia do Caminhoneiro - Setembro',
        '09/19': 'Dia Nacional do Educador Social, Dia do Ortopedista - Setembro',
        '09/20': 'Dia do Engenheiro Químico, Dia do Funcionário Municipal - Setembro',
        '09/21': 'Dia da Árvore, Dia do Fazendeiro, Início da Primavera - Setembro',
        '09/22': 'Dia da Aurora, Dia do Contador - Setembro',
        '09/23': 'Dia da Aurora, Dia do Soldador, Dia do Técnico em Edificações, Dia do Técnico Industrial - Setembro',
        '09/25': 'Dia do Hipnólogo, Dia Nacional da Rádio, Dia Internacional do Farmacêutico - Setembro',
        '09/26': 'Dia Nacional dos Surdos - Setembro',
        '09/27': 'Dia do Encanador, Dia Nacional do Turismólogo e dos Profissionais do Turismo - Setembro',
        '09/28': 'Dia do Hidrógrafo - Setembro',
        '09/29': 'Dia do Anunciante - Setembro',
        '09/30': 'Dia da Secretaria, Dia Mundial do Tradutor, Dia Nacional do Jornaleiro - Setembro',

        //OUTUBRO
        '10/01': 'Dia do Vendedor, Dia do Representante Comercial, Dia do Vereador - Outubro',
        '10/03': 'Dia Mundial do Dentista - Outubro',
        '10/04': 'Dia do Agente Comunitário de Saúde, Dia do Barman, Dia do Médico do Trabalho - Outubro',
        '10/05': 'Dia Mundial dos Professores - Outubro',
        '10/06': 'Dia do Tecnólogo - Outubro',
        '10/07': 'Dia do Compositor Brasileiro - Outubro',
        '10/08': 'Dia do Nordestino - Outubro',
        '10/12': 'Dia das Crianças, Dia de Nossa Senhora Aparecida, Dia do Engenheiro Agrônomo, Dia do Corretor de Seguros - Outubro',
        '10/13': 'Dia Nacional do Fisioterapeuta, Dia do Terapeuta Ocupacional - Outubro',
        '10/14': 'Dia do Meteorologista - Outubro',
        '10/15': 'Dia do Professor, Dia do Educador Ambiental - Outubro',
        '10/16': 'Dia do Anestesiologista, Dia do Chefe, Dia do Engenheiro de Alimentos - Outubro',
        '10/17': 'Dia do Eletricista, Dia do Profissional da Propaganda - Outubro',
        '10/18': 'Dia do Médico, Dia do Estivador, Dia do Pintor, Dia do Securitário - Outubro',
        '10/19': 'Dia do Guarda Noturno, Dia do Profissional de Informática, Dia do Profissional de Tecnologia da Informação, Dia do Operador de Caixa - Outubro',
        '10/20': 'Dia do Arquivista, Dia do Maquinista, Dia Mundial do Controlador de Tráfego Aéreo, Dia do Poeta - Outubro',
        '10/22': 'Dia do Enólogo, Dia do Paraquedista - Outubro',
        '10/23': 'Dia do Aviador, Dia do Engenheiro Eletricista - Outubro',
        '10/25': 'Dia do Dentista, Dia do Engenheiro Civil, Dia do Sapateiro - Outubro',
        '10/26': 'Dia do Trabalhador da Construção Civil, Dia do Vendedor de Livros - Outubro',
        '10/28': 'Dia do Funcionário Público - Outubro',
        '10/30': 'Dia do Balconista - Outubro',
        '10/31': 'Dia das Bruxas, Halloween, Dia Mundial do Comissário de Voo, Dia do Saci, Dia do Servidor Público - Outubro',

        //NOVEMBRO
        '11/02': 'Finados - Novembro',
        '11/03': 'Dia do Guarda - Novembro',
        '11/05': 'Dia do Cinema Brasileiro - Novembro',
        '11/08': 'Dia Mundial do Urbanismo, Dia do Radiologista - Novembro',
        '11/09': 'Dia do Hoteleiro - Novembro',
        '11/10': 'Dia do Trigo - Novembro',
        '11/11': 'Dia do Soldado Desconhecido - Novembro',
        '11/12': 'Dia do Diretor de Escola, Dia do Supermercado, Dia do Psicopedagogo - Novembro',
        '11/14': 'Dia do Bandeirante, Dia Nacional da Alfabetização - Novembro',
        '11/15': 'Proclamação da República - Novembro',
        '11/16': 'Dia Internacional para a Tolerância - Novembro',
        '11/17': 'Dia da Criatividade - Novembro',
        '11/19': 'Dia da Bandeira, Dia do Auditor Interno - Novembro',
        '11/20': 'Dia da Consciência Negra - Novembro',
        '11/21': 'Dia da Homeopatia - Novembro',
        '11/22': 'Dia do Músico - Novembro',
        '11/23': 'Dia do Engenheiro Eletricista - Novembro',
        '11/25': 'Dia Internacional pela Eliminação da Violência contra as Mulheres - Novembro',
        '11/28': 'Dia Mundial de Ação de Graças - Novembro',
        '11/29': 'Dia Internacional de Solidariedade com o Povo Palestino, Dia do Mecânico - Novembro',
        '11/30': 'Dia do Síndico, Dia do Estatuto da Terra - Novembro',

        //DEZEMBRO
        '12/01': 'Dia do Imigrante - Dezembro',
        '12/02': 'Dia do Samba, Dia Nacional da Astronomia - Dezembro',
        '12/03': 'Dia do Deficiente Físico, Dia Internacional do Portador de Deficiência - Dezembro',
        '12/04': 'Dia do Pedicuro, Dia do Orientador Educacional - Dezembro',
        '12/05': 'Dia Internacional do Voluntário, Dia do Vizinho - Dezembro',
        '12/07': 'Dia do Fonoaudiólogo, Dia do Craque do Futebol - Dezembro',
        '12/08': 'Dia da Família, Dia da Justiça, Dia do Cronista Esportivo - Dezembro',
        '12/09': 'Dia do Fonoaudiólogo, Dia do Alcoólico Recuperado - Dezembro',
        '12/10': 'Dia Internacional dos Direitos Humanos, Dia do Palhaço - Dezembro',
        '12/11': 'Dia do Arquiteto e Urbanista - Dezembro',
        '12/12': 'Dia de Nossa Senhora de Guadalupe, Dia do Engenheiro Florestal - Dezembro',
        '12/13': 'Dia do Marinheiro - Dezembro',
        '12/14': 'Dia Nacional do Ministério Público - Dezembro',
        '12/15': 'Dia do Jardineiro, Dia do Jogo Justo - Dezembro',
        '12/16': 'Dia do Reservista - Dezembro',
        '12/17': 'Dia do Farmacêutico, Dia do Bibliotecário - Dezembro',
        '12/18': 'Dia do Museólogo, Dia do Sargento, Dia Internacional do Migrante - Dezembro',
        '12/20': 'Dia do Mecânico, Dia do Arquiteto - Dezembro',
        '12/21': 'Dia do Atleta, Início do Verão (2024) - Dezembro',
        '12/22': 'Dia do Jardineiro, Dia do Vendedor de Livros, Dia do Contador - Dezembro',
        '12/23': 'Dia do Vizinho - Dezembro',
        '12/24': 'Dia da Gratidão, Véspera de Natal - Dezembro',
        '12/25': 'Natal - Dezembro',
        '12/26': 'Dia da Lembrança, Dia do Especialista de Aeronáutica, Dia da Propaganda - Dezembro',
        '12/27': 'Dia do Biomédico, Dia do Terapeuta Ocupacional, Dia do Engenheiro Sanitarista - Dezembro',
        '12/28': 'Dia do Salva-Vidas - Dezembro',
        '12/29': 'Dia da Confraternização Universal - Dezembro',
        '12/30': 'Dia do Comissário de Menores, Dia do Seguro - Dezembro',
        '12/31': 'Reveillon, Dia de São Silvestre - Dezembro',

        // Adicione mais datas conforme necessário
    };

    const chave = `${mes.toString().padStart(2, '0')}/${dia.toString().padStart(2, '0')}`;
    return datasComemorativas[chave] || "Nenhuma comemoração hoje.";
}

// Exibir data comemorativa na página
const dataComemorativa = nomearDataComemorativa();
document.getElementById("dataComemorativa").textContent = dataComemorativa;
